enum RolUsuario {
  CLIENTE
  ADMIN
}

enum CategoriaProducto {
  HAMBURGUESAS
  PAPAS
  BEBIDAS
  POSTRES
}

enum EstadoPedido {
  PREPARING
  COMPLETED
  CANCELLED
}

enum ModalidadEntrega {
  DELIVERY
  TAKEAWAY
}

type Usuario @table {
  nombreCompleto: String!
  email: String! @unique
  passwordHash: String!
  rol: RolUsuario! @default(value: CLIENTE)
  createdAt: Timestamp! @default(expr: "request.time")
}

type Producto @table {
  nombre: String!
  descripcion: String!
  ingredientes: String
  precio: Int!
  categoria: CategoriaProducto!
  imagenUrl: String!
  activo: Boolean! @default(value: true)
  createdAt: Timestamp! @default(expr: "request.time")
}

type Pedido @table {
  codigo: String! @unique
  usuario: Usuario!
  estado: EstadoPedido! @default(value: PREPARING)
  subtotal: Int!
  costoEnvio: Int!
  total: Int!
  modalidadEntrega: ModalidadEntrega!
  nombreContacto: String!
  telefonoContacto: String!
  direccion: String
  createdAt: Timestamp! @default(expr: "request.time")
}

type PedidoItem @table {
  pedido: Pedido!
  producto: Producto
  nombreProducto: String!
  cantidad: Int!
  precioUnitario: Int!
  precioTotalLinea: Int!
  extraMedallon: Int! @default(value: 0)
  extraCheddar: Int! @default(value: 0)
  extraPanceta: Int! @default(value: 0)
  extraCebolla: Int! @default(value: 0)
  notas: String
}
